### ISSUE TITLE
Run `make check` in CI

### ISSUE THREAD

**Issue by martinpitt** [jelly/console.dot#5]
We can run websocat | bridge right inside the session pod for this, so that we don't have to spawn VMs.

**Comment by jelly** [comment]
Setup a test Python `unittest` framework with a GH workflow

**Comment by martinpitt** [comment]
`make check` is implemented. But running this in GitHub hits about a dozen different walls -- podman's version in Ubuntu 20.04 and 22.04 does not work properly (image builds crashing, pods not talking to each other), neither as user nor as root. We also tried to run the test in a privileged container, but without systemd the podman operations don't work either. So far we haven't found any working combination.
